### ISSUE TITLE
DLLs - Win somente?

### ISSUE THREAD

**Issue by tavinus** [JoseQuintas/sefazclass#10]
Olá! Parabéns pelo trabalho!  
E obrigado por disponibilizar tudo aqui.  
  
Eu estava me perguntando sobre as `DLLs necessárias`.  
O seu pacote é somente para Windows?  
  
Notei que uma das DLLs é referente à xml.  
Essa parte ficaria quebrada no Linux?  
  
Obrigado.

**Comment by JoseQuintas** [comment]
As DLLs são pra assinatura e comunicação.
Teria que substituir por outras no Linux, LibCurl e OpenSSL além de ajustar as rotinas pra elas.

**Comment by tavinus** [comment]
Entendi!    
  
Estou ajudando a migrar um sistema em ITK/Clip para o Harbour  
e agora chegamos na parte de XML e não sei direito o que fazer.   
  
Eles usavam XMLTREE do Clip pra processar o XML e como isso  
não tem no Harbour, vamos ter que criar isso ou mudar toda a parte de XML.  
  
Como é quase tudo pra lidar com CTe e MDFe, pensei que talvez suas classes  
pudessem substituir o que é usado atualmente, mas é pra rodar em Linux.  
  
Na real a toda a parte de comunicação com o sefaz está usando NFePHP, mas o sistema  
em si é em Clip.
  
Duro que pra portar a Classe XMLTREE do Clip (e as auxiliares dela) não aprece muito viável.  
Ter um drop-in replacement seria o ideal pra poder migrar sem mudar muita coisa, mas tá difícil.  
  
Pra piorar eu estou faz 20 anos em outras linguagens e nem lembro direito de Clipper/Harbour  
(apesar de Clipper Summer 87 ter sido a primeira linguagem que eu programei).  
  
Obrigado pelas respostas e tbm por suas postagens no pctoledo, já me ajuda bastante!  
Acho que pode fechar aqui...
  
Cheers!  
Gus
