### ISSUE TITLE
Ainda em funcionamento?

### ISSUE THREAD

**Issue by angeloreis** [JoseQuintas/sefazclass#13]
Bom dia. achei seu repositório em um pesquisa.

Este seu componente está atualizado com as NT da SEFAZ?

Att,

**Comment by JoseQuintas** [comment]
Vamos inverter a pergunta.... PORQUE atualizar pras NTs?
Talvez esteja acostumando com componentes que deixam o usuário preso a atualizações, e nem percebeu que não precisaria delas.

**Comment by angeloreis** [comment]
Beleza. Mas, o seu readme não informa sobre a versão. Poderia ser na 3.10 ou até mesmo na 2.0 não adiantaria nada usar em um sistema legado, a qual estou dando suporte!

**Comment by JoseQuintas** [comment]
Você está certo, readme.md atualizado.
