### ISSUE TITLE
Definir folha de tamanho carta

### ISSUE THREAD

**Issue by jparadaa** [JoseQuintas/sefazclass#16]
Olá José, estou a tentar voltar a utilizar o pdfclass, já tentei uma vez mas não funcionou como eu esperava, nessa altura como não conseguia gerar pdf utilizei o excel sem problemas, mas agora é obrigatório para o meu trabalho utilizar o pdf, por isso tenho algumas questões, por favor.
Utilizo um tamanho de folha padrão que é o tamanho Letter, vejo que a vossa classe lida por defeito com o tamanho A4, por isso pergunto-vos se basta substituir os tamanhos.

VAR nPageWidth INIT 612
VAR nPageHeight INIT 792

e a próxima pergunta é como posso inserir uma imagem png, qual é o método na classe para o fazer.

Agradeço o vosso tempo e qualquer ajuda

**Comment by JoseQuintas** [comment]
A classe usa a harupdf. Se não tiver a opção é só criar.
consultando no harbour:
hbmk2 -find png
hbhpdf.hbc (installed):
   HPDF_LoadPngImageFromFile()
   HPDF_LoadPngImageFromFile2()
   HPDF_LoadPngImageFromMem()

Quanto ao tamanho da folha, é só alterar isso mesmo, ou na classe, ou atribuir antes do begin.

**Comment by JoseQuintas** [comment]
Fiz a alteração pra PNG, mas sem testes. Estranhei ter duas funções pra carregar png. Considerei que devem ser iguais a de JPEG.

**Comment by jparadaa** [comment]
Olá, obrigado por responder, então está a dizer-me que, em termos de tamanho da folha, posso simplesmente indicá-lo com as variáveis, assim:

```
oPDF := PDFClass():New()
oPDF:Begin()
oPDF:cFileName := tempFile
oPDF:nPageWidth := 612 
oPDF:nPageHeight := 792
```

e isso seria tudo, não teria de fazer mais nada, no método SetType indica explicitamente o tamanho A4, daí a minha dúvida.

```
METHOD SetType( nPrinterType ) CLASS PDFClass

   IF nPrinterType != NIL
      ::nPrinterType := nPrinterType
   ENDIF
   DO CASE
   CASE ::nPrinterType == PDFCLASS_PORTRAIT
      ::nFontSize   := 9
      ::nPageWidth  := 841.89 // A4
      ::nPageHeight := 595.28 // A4
   CASE ::nPrinterType == PDFCLASS_LANDSCAPE
      ::nFontSize   := 6
      ::nPageWidth  := 595.28 // A4
      ::nPageHeight := 841.89 // A4
   CASE ::nPrinterType == PDFCLASS_TXT
      ::nPageWidth  := 132
      ::nPageHeight := 66
   ENDCASE

RETURN NIL
```

Quanto à tua resposta sobre a adição de PNG, não vejo que o código-fonte do repositório sefazclass tenha sido atualizado, mas vou ver se consigo adicioná-lo.

**Comment by JoseQuintas** [comment]
Me esqueci de salvar as alterações ontem.
SetType() é necessário pra definir formato de saída.
Depois dele, coloque as alterações de tamanho.
Primeiro configure, depois o Begin()

**Comment by jparadaa** [comment]
Olá, peço desculpa pelo atraso, vou certamente continuar com os testes, tenho tentado uma aula e outra, tentando resolver as minhas necessidades, claro que devido à minha falta de conhecimentos.
